name: BetterMusic
version: ${project.version}
main: play.criticalcraft.bettermusic.BetterMusic
api-version: 1.13
depend:
  - MCJukebox
commands:
  bm:
    description: Base command for BetterMusic
    usage: /<command>

